export const LAYOUTS = {
  VARIANT0: 0,
  VARIANT1: 1,
  VARIANT2: 2
};
export const VARIANTS_WITH_LABEL_INSIDE = [LAYOUTS.VARIANT0, LAYOUTS.VARIANT1];
export const VARIANTS_WITH_BORDER = [LAYOUTS.VARIANT0, LAYOUTS.VARIANT2];
